import type { Metadata } from "next";
import '@repo/ui/globals.css'

import Navbarish from "./lib/components/NavigationBar";
import {Inter} from "next/font/google";

const inter = Inter({
  subsets: ['cyrillic'],
  weight:"variable",
  variable:"--font-sans"
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <Navbarish/>
      
        {children}
      </body>
    </html>
  );
}
