import type { Metadata } from "next";
import '@repo/ui/globals.css';

import NavbarWrapper from "./lib/components/navwrapper"; // Correct import
import { Inter } from "next/font/google";
import { Toaster } from "@repo/ui/components/ui/toaster";

const inter = Inter({
  weight: "variable",
  variable: "--font-sans",
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Connectogen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <NavbarWrapper /> {/* Ensure it's rendered inside the body */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
